# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://aloiswirth.github.io/Python_training/"

git_url = "https://github.com/aloiswirth/Python_training/tree/main/"

def custom_doc_links(name): return None
